<?php

namespace ContainerXHjmHvP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_UdTvH3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.udTvH3_' shared service.
     *
     * @return \App\Controller\TutoRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\TutoController::index()": the $productRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\TutoRepository". Did you forget to add a use statement?');
    }
}
