<?php

namespace ContainerXHjmHvP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserCrudControllercreateIndexQueryBuilderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.a135s2Q.App\Controller\Admin\UserCrudController::createIndexQueryBuilder()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.a135s2Q.App\\Controller\\Admin\\UserCrudController::createIndexQueryBuilder()'] = ($container->privates['.service_locator.a135s2Q'] ?? $container->load('get_ServiceLocator_A135s2QService'))->withContext('App\\Controller\\Admin\\UserCrudController::createIndexQueryBuilder()', $container);
    }
}
