<?php

namespace ContainerO13hibJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OwZO7CZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.owZO7CZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.owZO7CZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'productRepository' => ['privates', '.errored.udTvH3_', NULL, 'Cannot determine controller argument for "App\\Controller\\TutoController::index()": the $productRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\TutoRepository". Did you forget to add a use statement?'],
        ], [
            'productRepository' => '?',
        ]);
    }
}
