<?php

namespace ContainerO13hibJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAchatProduitControllerMerciService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vJmVCmb.App\Controller\AchatProduitController::Merci()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vJmVCmb.App\\Controller\\AchatProduitController::Merci()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ProduitRepository' => ['privates', 'App\\Repository\\ProduitsRepository', 'getProduitsRepositoryService', true],
        ], [
            'ProduitRepository' => 'App\\Repository\\ProduitsRepository',
        ]))->withContext('App\\Controller\\AchatProduitController::Merci()', $container);
    }
}
