<?php

namespace ContainerO13hibJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mXDaS5b.App\Controller\ClientController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mXDaS5b.App\\Controller\\ClientController::index()'] = ($container->privates['.service_locator.mXDaS5b'] ?? $container->load('get_ServiceLocator_MXDaS5bService'))->withContext('App\\Controller\\ClientController::index()', $container);
    }
}
